# Generated by Django 2.2.6 on 2019-10-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0003_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='weather',
            field=models.CharField(default='Sunny', max_length=20),
        ),
        migrations.AddField(
            model_name='essay',
            name='weather',
            field=models.CharField(default='Sunny', max_length=20),
        ),
        migrations.AddField(
            model_name='files',
            name='weather',
            field=models.CharField(default='Sunny', max_length=20),
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
